export default function TermsOfService() {
  return (
    <div className="page">
      <div className="container" style={{ maxWidth: 720, paddingTop: 40, paddingBottom: 60 }}>
        <h1 style={{ fontSize: 24, fontWeight: 700, marginBottom: 8 }}>Terms of Service</h1>
        <p style={{ fontSize: 13, color: 'var(--color-text-secondary)', marginBottom: 32 }}>
          Last updated: March 19, 2026
        </p>

        <div style={{ fontSize: 14, lineHeight: 1.7, color: 'var(--color-text)' }}>
          <p>
            These Terms of Service ("Terms") govern your use of AddFi, a financial management application
            operated by Milos Kasapovic ("we," "us," or "our"), accessible at addfi.co. By accessing or
            using AddFi, you agree to be bound by these Terms.
          </p>

          <h2 style={{ fontSize: 18, fontWeight: 600, marginTop: 28, marginBottom: 12 }}>1. Acceptance of Terms</h2>
          <p>
            By creating an account or using AddFi, you confirm that you are at least 18 years old and agree
            to comply with these Terms. If you do not agree, do not use the service.
          </p>

          <h2 style={{ fontSize: 18, fontWeight: 600, marginTop: 28, marginBottom: 12 }}>2. Description of Service</h2>
          <p>
            AddFi is a cloud-based financial tracking and invoicing tool designed for small businesses.
            Features include expense and income tracking, invoice creation and management, receipt scanning,
            reporting, client management, and job scheduling. Certain features are available only on paid
            subscription plans.
          </p>

          <h2 style={{ fontSize: 18, fontWeight: 600, marginTop: 28, marginBottom: 12 }}>3. Not Financial or Tax Advice</h2>
          <p>
            AddFi is a record-keeping tool only. We do not provide accounting, tax, legal, or financial
            advice. The reports and calculations generated by AddFi are for informational purposes only
            and should not be relied upon as a substitute for professional financial advice. You are solely
            responsible for the accuracy of the data you enter and for complying with applicable tax laws.
            We strongly recommend consulting a qualified accountant or tax professional for financial decisions.
          </p>

          <h2 style={{ fontSize: 18, fontWeight: 600, marginTop: 28, marginBottom: 12 }}>4. Accounts</h2>
          <p>
            You are responsible for maintaining the confidentiality of your account credentials and for all
            activity that occurs under your account. You agree to provide accurate information when creating
            your account and to notify us immediately of any unauthorized use. We reserve the right to
            suspend or terminate accounts that violate these Terms.
          </p>

          <h2 style={{ fontSize: 18, fontWeight: 600, marginTop: 28, marginBottom: 12 }}>5. Subscription Plans and Billing</h2>
          <p>
            AddFi offers free and paid subscription plans. Paid plans are billed monthly or annually through
            Stripe. By subscribing to a paid plan, you authorize us to charge your payment method on a
            recurring basis until you cancel. You may cancel your subscription at any time through the app
            or by contacting us at support@addfi.co.
          </p>
          <p style={{ marginTop: 8 }}>
            Prices are subject to change with 30 days' notice. Refunds are handled on a case-by-case basis
            at our discretion.
          </p>

          <h2 style={{ fontSize: 18, fontWeight: 600, marginTop: 28, marginBottom: 12 }}>6. Invoice Payment Processing</h2>
          <p>
            AddFi may offer the ability for your clients to pay invoices online through a client portal.
            Payments are processed by Stripe. A processing fee of 3.5% applies to each transaction paid
            through the portal. We are not responsible for payment disputes between you and your clients.
            You are responsible for complying with all applicable payment and tax regulations.
          </p>

          <h2 style={{ fontSize: 18, fontWeight: 600, marginTop: 28, marginBottom: 12 }}>7. Your Data</h2>
          <p>
            You retain ownership of all data you enter into AddFi, including transactions, invoices, client
            information, receipts, and business records. We do not claim any ownership rights over your content.
            You may export or delete your data at any time through the app.
          </p>

          <h2 style={{ fontSize: 18, fontWeight: 600, marginTop: 28, marginBottom: 12 }}>8. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul style={{ paddingLeft: 20, marginTop: 8 }}>
            <li>Use AddFi for any illegal purpose or to facilitate fraud</li>
            <li>Attempt to access other users' accounts or data</li>
            <li>Reverse engineer, decompile, or disassemble the application</li>
            <li>Upload malicious files or content</li>
            <li>Resell or redistribute AddFi without our written consent</li>
            <li>Use automated systems to scrape or extract data from the service</li>
          </ul>

          <h2 style={{ fontSize: 18, fontWeight: 600, marginTop: 28, marginBottom: 12 }}>9. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, AddFi and its operator shall not be liable for any
            indirect, incidental, special, consequential, or punitive damages, including but not limited to
            loss of profits, data, or business opportunities, arising out of or related to your use of
            the service.
          </p>
          <p style={{ marginTop: 8 }}>
            Our total liability for any claim arising from these Terms or your use of AddFi shall not
            exceed the amount you paid us in the 12 months preceding the claim.
          </p>
          <p style={{ marginTop: 8 }}>
            We do not guarantee that the service will be uninterrupted, error-free, or that any data will
            be preserved indefinitely. You are responsible for maintaining your own backups.
          </p>

          <h2 style={{ fontSize: 18, fontWeight: 600, marginTop: 28, marginBottom: 12 }}>10. Disclaimer of Warranties</h2>
          <p>
            AddFi is provided "as is" and "as available" without warranties of any kind, whether express
            or implied, including but not limited to implied warranties of merchantability, fitness for a
            particular purpose, and non-infringement. We do not warrant that calculations, reports, or any
            output generated by AddFi are accurate or complete.
          </p>

          <h2 style={{ fontSize: 18, fontWeight: 600, marginTop: 28, marginBottom: 12 }}>11. Indemnification</h2>
          <p>
            You agree to indemnify and hold harmless Milos Kasapovic and AddFi from any claims, damages,
            losses, or expenses (including reasonable attorneys' fees) arising from your use of the service,
            your violation of these Terms, or your violation of any third-party rights.
          </p>

          <h2 style={{ fontSize: 18, fontWeight: 600, marginTop: 28, marginBottom: 12 }}>12. Termination</h2>
          <p>
            We may suspend or terminate your access to AddFi at any time, with or without cause, with or
            without notice. Upon termination, your right to use the service ceases immediately. You may
            request an export of your data before or within 30 days after termination by contacting
            support@addfi.co.
          </p>

          <h2 style={{ fontSize: 18, fontWeight: 600, marginTop: 28, marginBottom: 12 }}>13. Changes to These Terms</h2>
          <p>
            We may update these Terms from time to time. We will notify you of material changes by posting
            the updated Terms on the app and updating the "Last updated" date. Your continued use of AddFi
            after changes are posted constitutes acceptance of the revised Terms.
          </p>

          <h2 style={{ fontSize: 18, fontWeight: 600, marginTop: 28, marginBottom: 12 }}>14. Governing Law</h2>
          <p>
            These Terms are governed by and construed in accordance with the laws of the State of Illinois,
            United States, without regard to its conflict of law provisions. Any disputes arising under
            these Terms shall be subject to the exclusive jurisdiction of the courts located in Illinois.
          </p>

          <h2 style={{ fontSize: 18, fontWeight: 600, marginTop: 28, marginBottom: 12 }}>15. Contact</h2>
          <p>
            If you have questions about these Terms, contact us at:<br />
            <strong>Email:</strong> support@addfi.co
          </p>
        </div>
      </div>
    </div>
  );
}
