import PDFDocument from 'pdfkit';

export function generateInvoicePDF(invoice, user) {
  return new Promise((resolve) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));

    // Header
    doc.fontSize(24).fillColor('#4A90E2').text(user.business_name || 'My Business', 50, 50);
    doc.fontSize(10).fillColor('#8E8E93').text(user.email, 50, 80);

    // Invoice title
    doc.fontSize(28).fillColor('#1C1C1E').text('INVOICE', 400, 50, { align: 'right' });
    doc.fontSize(12).fillColor('#8E8E93').text(invoice.invoice_number, 400, 85, { align: 'right' });

    doc.moveDown(3);

    // Bill To
    const infoY = 130;
    doc.fontSize(10).fillColor('#8E8E93').text('BILL TO', 50, infoY);
    doc.fontSize(12).fillColor('#1C1C1E').text(invoice.client_name, 50, infoY + 16);
    if (invoice.client_email) {
      doc.fontSize(10).fillColor('#8E8E93').text(invoice.client_email, 50, infoY + 32);
    }

    // Dates
    doc.fontSize(10).fillColor('#8E8E93').text('ISSUE DATE', 350, infoY);
    doc.fontSize(11).fillColor('#1C1C1E').text(formatDate(invoice.issue_date), 350, infoY + 16);

    doc.fontSize(10).fillColor('#8E8E93').text('DUE DATE', 350, infoY + 40);
    doc.fontSize(11).fillColor('#1C1C1E').text(formatDate(invoice.due_date), 350, infoY + 56);

    // Status badge
    const statusColors = { draft: '#8E8E93', sent: '#4A90E2', paid: '#34C759', overdue: '#FF3B30' };
    doc.fontSize(10).fillColor(statusColors[invoice.status] || '#8E8E93')
      .text(invoice.status.toUpperCase(), 350, infoY + 80);

    // Line items table
    let tableY = 240;

    // Table header
    doc.rect(50, tableY, 510, 24).fill('#F5F7FA');
    doc.fontSize(9).fillColor('#8E8E93');
    doc.text('DESCRIPTION', 60, tableY + 7, { width: 250 });
    doc.text('QTY', 320, tableY + 7, { width: 50, align: 'center' });
    doc.text('RATE', 380, tableY + 7, { width: 80, align: 'right' });
    doc.text('AMOUNT', 470, tableY + 7, { width: 80, align: 'right' });

    tableY += 30;

    // Table rows
    doc.fillColor('#1C1C1E').fontSize(10);
    for (const item of invoice.items) {
      doc.text(item.description, 60, tableY, { width: 250 });
      doc.text(String(item.quantity), 320, tableY, { width: 50, align: 'center' });
      doc.text(`$${parseFloat(item.rate).toFixed(2)}`, 380, tableY, { width: 80, align: 'right' });
      doc.text(`$${parseFloat(item.amount).toFixed(2)}`, 470, tableY, { width: 80, align: 'right' });

      tableY += 22;

      // Line separator
      doc.moveTo(50, tableY - 4).lineTo(560, tableY - 4).strokeColor('#E5E5EA').lineWidth(0.5).stroke();
    }

    // Totals
    tableY += 16;
    doc.fontSize(10).fillColor('#8E8E93').text('Subtotal', 380, tableY, { width: 80, align: 'right' });
    doc.fillColor('#1C1C1E').text(`$${parseFloat(invoice.subtotal).toFixed(2)}`, 470, tableY, { width: 80, align: 'right' });

    if (parseFloat(invoice.tax_rate) > 0) {
      tableY += 20;
      doc.fillColor('#8E8E93').text(`Tax (${invoice.tax_rate}%)`, 380, tableY, { width: 80, align: 'right' });
      doc.fillColor('#1C1C1E').text(`$${parseFloat(invoice.tax_amount).toFixed(2)}`, 470, tableY, { width: 80, align: 'right' });
    }

    tableY += 24;
    doc.rect(370, tableY - 4, 190, 28).fill('#F5F7FA');
    doc.fontSize(13).fillColor('#1C1C1E').text('Total', 380, tableY + 2, { width: 80, align: 'right' });
    doc.text(`$${parseFloat(invoice.total).toFixed(2)}`, 470, tableY + 2, { width: 80, align: 'right' });

    // Notes
    if (invoice.notes) {
      tableY += 50;
      doc.fontSize(10).fillColor('#8E8E93').text('NOTES', 50, tableY);
      doc.fillColor('#1C1C1E').text(invoice.notes, 50, tableY + 16, { width: 400 });
    }

    // Footer
    doc.fontSize(8).fillColor('#8E8E93').text(
      'Generated by FlowFi',
      50, 750, { align: 'center', width: 510 }
    );

    doc.end();
  });
}

function formatDate(dateStr) {
  const d = new Date(dateStr);
  return d.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
}
