import PDFDocument from 'pdfkit';

export function generatePDF(data) {
  return new Promise((resolve) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));

    const pageWidth = doc.page.width;
    const contentWidth = pageWidth - 100;

    // Accent bar at top
    doc.rect(0, 0, pageWidth, 6).fill('#4A90E2');

    // Header
    const headerY = 40;
    doc.fontSize(22).fillColor('#1C1C1E')
      .text(data.businessName, 50, headerY);

    if (data.businessAddress) {
      doc.fontSize(9).fillColor('#8E8E93')
        .text(data.businessAddress, 50, headerY + 28);
    }

    doc.fontSize(32).fillColor('#4A90E2')
      .text('P&L', 350, headerY, { align: 'right', width: contentWidth - 300 });

    // Date range
    doc.fontSize(10).fillColor('#8E8E93')
      .text(`${formatDate(data.dateFrom)} — ${formatDate(data.dateTo)}`, 350, headerY + 38, { align: 'right', width: contentWidth - 300 });

    // Divider
    doc.moveTo(50, 100).lineTo(pageWidth - 50, 100)
      .strokeColor('#E5E5EA').lineWidth(1).stroke();

    let y = 120;

    // Income section
    y = drawSection(doc, 'INCOME', data.income, data.totalIncome, '#34C759', y, contentWidth, data.currency);

    y += 20;

    // Expenses section
    y = drawSection(doc, 'EXPENSES', data.expenses, data.totalExpenses, '#FF3B30', y, contentWidth, data.currency);

    y += 24;

    // Net Profit
    doc.moveTo(50, y).lineTo(pageWidth - 50, y)
      .strokeColor('#E5E5EA').lineWidth(1).stroke();
    y += 12;

    const profitColor = data.netProfit >= 0 ? '#34C759' : '#FF3B30';
    const totalBoxW = 240;
    const totalBoxX = pageWidth - 50 - totalBoxW;

    doc.roundedRect(totalBoxX, y, totalBoxW, 40, 6).fill(profitColor);
    doc.fontSize(12).fillColor('#FFFFFF').font('Helvetica-Bold')
      .text('NET PROFIT', totalBoxX + 16, y + 13);
    doc.fontSize(16)
      .text(`${formatCurrency(data.netProfit, data.currency)}`, totalBoxX + 100, y + 11, { width: totalBoxW - 116, align: 'right' });

    // Footer
    doc.font('Helvetica');
    const footerY = y + 70;
    doc.moveTo(50, footerY).lineTo(pageWidth - 50, footerY)
      .strokeColor('#E5E5EA').lineWidth(0.5).stroke();

    doc.fontSize(8).fillColor('#B0B7C3')
      .text(`Generated by AddFi on ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}`, 50, footerY + 8, { align: 'center', width: contentWidth });

    doc.end();
  });
}

function drawSection(doc, title, items, total, color, startY, contentWidth, currency) {
  const pageWidth = doc.page.width;
  let y = startY;

  // Section header
  doc.rect(50, y, contentWidth, 28).fill('#F8F9FB');
  doc.fontSize(9).fillColor(color).font('Helvetica-Bold')
    .text(title, 62, y + 9, { width: 200 });
  doc.fillColor('#8E8E93').fontSize(8)
    .text('COUNT', 340, y + 9, { width: 50, align: 'center' });
  doc.text('AMOUNT', 400, y + 9, { width: 130, align: 'right' });

  y += 34;

  // Rows
  doc.font('Helvetica');
  let isAlt = false;
  for (const item of items) {
    if (isAlt) {
      doc.rect(50, y - 3, contentWidth, 24).fill('#FAFBFC');
    }

    doc.fontSize(10).fillColor('#1C1C1E')
      .text(item.category || 'Uncategorized', 62, y + 2, { width: 260 });
    doc.fillColor('#6B7280').fontSize(9)
      .text(String(item.count), 340, y + 3, { width: 50, align: 'center' });
    doc.fillColor('#1C1C1E').fontSize(10)
      .text(formatCurrency(parseFloat(item.total), currency), 400, y + 2, { width: 130, align: 'right' });

    y += 24;
    isAlt = !isAlt;
  }

  if (items.length === 0) {
    doc.fontSize(10).fillColor('#8E8E93')
      .text('No items', 62, y + 2);
    y += 24;
  }

  // Section total
  doc.moveTo(300, y).lineTo(pageWidth - 50, y)
    .strokeColor('#E5E5EA').lineWidth(0.5).stroke();
  y += 8;

  doc.fontSize(11).fillColor('#1C1C1E').font('Helvetica-Bold')
    .text(`Total ${title.charAt(0) + title.slice(1).toLowerCase()}`, 300, y, { width: 100, align: 'right' });
  doc.text(formatCurrency(total, currency), 400, y, { width: 130, align: 'right' });

  doc.font('Helvetica');
  return y + 20;
}

function formatDate(dateStr) {
  return new Date(dateStr).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
}

function formatCurrency(amount, currency = 'USD') {
  return new Intl.NumberFormat('en-US', { style: 'currency', currency }).format(amount);
}
