import PDFDocument from 'pdfkit';

export function generatePDF(data) {
  return new Promise((resolve) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));

    // Header
    doc.fontSize(20).text(data.businessName, { align: 'center' });
    doc.fontSize(12).text('Profit & Loss Report', { align: 'center' });
    doc.fontSize(10).text(`${data.dateFrom} to ${data.dateTo}`, { align: 'center' });
    doc.moveDown(2);

    // Income section
    doc.fontSize(14).fillColor('#34C759').text('Income');
    doc.fillColor('#000000');
    doc.moveDown(0.5);

    for (const item of data.income) {
      doc.fontSize(10).text(`  ${item.category || 'Uncategorized'}`, { continued: true });
      doc.text(`  $${parseFloat(item.total).toFixed(2)}`, { align: 'right' });
    }
    doc.moveDown(0.5);
    doc.fontSize(11).text('Total Income', { continued: true });
    doc.text(`  $${data.totalIncome.toFixed(2)}`, { align: 'right' });
    doc.moveDown(1.5);

    // Expenses section
    doc.fontSize(14).fillColor('#FF3B30').text('Expenses');
    doc.fillColor('#000000');
    doc.moveDown(0.5);

    for (const item of data.expenses) {
      doc.fontSize(10).text(`  ${item.category || 'Uncategorized'}`, { continued: true });
      doc.text(`  $${parseFloat(item.total).toFixed(2)}`, { align: 'right' });
    }
    doc.moveDown(0.5);
    doc.fontSize(11).text('Total Expenses', { continued: true });
    doc.text(`  $${data.totalExpenses.toFixed(2)}`, { align: 'right' });
    doc.moveDown(2);

    // Net Profit
    const profitColor = data.netProfit >= 0 ? '#34C759' : '#FF3B30';
    doc.fontSize(16).fillColor(profitColor).text(
      `Net Profit: $${data.netProfit.toFixed(2)}`,
      { align: 'center' }
    );

    doc.moveDown(2);
    doc.fontSize(8).fillColor('#888888').text(
      `Generated by FlowFi on ${new Date().toLocaleDateString()}`,
      { align: 'center' }
    );

    doc.end();
  });
}
